name: Build and Deploy Lib
on:
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true

      - name: Build Lib
        run: pnpm package

      - name: Publish Lib
        run: |
          cd package
          npm version ${{ github.event.release.tag_name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
