name: Lint & Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true

      - run: pnpm lint
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build
          start: pnpm preview
